DROP DATABASE IF EXISTS autDB;
CREATE DATABASE IF NOT EXISTS autDB;
USE autDB;

CREATE USER IF NOT EXISTS 'autUser'@'localhost' IDENTIFIED BY 'maninthemoon';
GRANT ALL PRIVILEGES ON autDB.* TO 'autUser'@'localhost';
FLUSH PRIVILEGES;


/* ---- AUT DB #1----- */
/*events - click, mouse, hover, tab, resize, scroll*//* add -- target */
CREATE TABLE IF NOT EXISTS click_table (
	logID INT AUTO_INCREMENT,	
    href TEXT,
	x INT,
	y INT,
	xscroll INT,
	yscroll INT,
	TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (logID)
);

CREATE TABLE IF NOT EXISTS tabing_table (
	logID INT AUTO_INCREMENT,
	href TEXT,
    tabs INT,/* count up total amount of tabs per page*/
	TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (logID)
);

CREATE TABLE IF NOT EXISTS browser_table (
	logID INT AUTO_INCREMENT,
	href TEXT,
	appCodeName TEXT,
	userAgent TEXT,
    ww INT,
	wh INT,
    sw INT,
	sh INT,
	TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (logID)
);

CREATE TABLE IF NOT EXISTS mousemove_table (
	logID INT AUTO_INCREMENT,
	href TEXT,
	mouseX INT,
	mouseY INT,
	TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (logID)
);

CREATE TABLE IF NOT EXISTS hover_table (
	logID INT AUTO_INCREMENT,
	href TEXT,
	target TEXT,
	countUpSec INT,
	TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (logID)
);

CREATE TABLE IF NOT EXISTS mousemoveComp_table (
	logID INT AUTO_INCREMENT,
	href TEXT,
	mouseX INT,
	mouseY INT,
    logSkips INT,
	TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (logID)
);